Add endpoint implementation of Instrument
nii236/oanda pull request #4
Opened 2016-12-06 22:41 UTC by lerenn

Hi !

As you've done a great job with the start of this API, I contributed for the part I needed.
If there is anything to change, just ask ;)

2016-12-07 06:18 UTC, nii236 requested changes

2016-12-07 06:18 UTC, nii236 commented on instrument_test.go
> +package oanda
No need for this file (delete)

2016-12-07 06:18 UTC, nii236 commented on models.go
> +// Candle contains informations concerning a candle
> Candle

Instead of 

> candle

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +////////////////////////////////////////////////////////////////////////////////
Please remove this line

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +////////////////////////////////////////////////////////////////////////////////
Please remove this line

2016-12-07 06:18 UTC, nii236 commented on examples/instruments.go
> +	loc, _ := time.LoadLocation("Europe/Paris")
Please check this error

2016-12-07 06:18 UTC, nii236 commented on examples/instruments.go
> +		//oanda.CandlesTo(time.Now().AddDate(0, -1, 0)), -> You can't set From and To at the same time
Please remove commented code

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (p CandlesPrice) applyCandlesArg(v *url.Values) {
Prefer `cp` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (g CandlesGranularity) applyCandlesArg(v *url.Values) {
Prefer `cg` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (c CandlesCount) applyCandlesArg(v *url.Values) {
Prefer `cc` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (f CandlesFrom) applyCandlesArg(v *url.Values) {
Prefer `cf` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (t CandlesTo) applyCandlesArg(v *url.Values) {
Prefer `ct` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (s CandlesSmooth) applyCandlesArg(v *url.Values) {
Prefer `cs` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (i CandlesIncludeFirst) applyCandlesArg(v *url.Values) {
Prefer `cif` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (da CandlesDailyAlign) applyCandlesArg(v *url.Values) {
Prefer `cda` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (at CandlesAlignTimezone) applyCandlesArg(v *url.Values) {
Prefer `cat` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented on instrument.go
> +func (wa CandlesWeeklyAlign) applyCandlesArg(v *url.Values) {
Prefer `cwa` for the struct receiver

2016-12-07 06:18 UTC, nii236 commented
Thanks so much for your contribution! Please make the minor changes above and I'll be happy to merge it in 👍

2016-12-07 19:07 UTC, lerenn commented
Done ! It should be as you expected it.

2016-12-08 00:42 UTC, merged

2016-12-08 00:42 UTC, nii236 commented
Awesome thanks for your contribution!